INSERT INTO MEMBER_TYPE (DESCRIPTION, AMOUNT) VALUES ( 'Vollmitglied', 25.0 );
INSERT INTO MEMBER_TYPE (DESCRIPTION, AMOUNT) VALUES ( 'Ermäßigt', 23.0 );
INSERT INTO MEMBER_TYPE (DESCRIPTION, AMOUNT) VALUES ( 'Jugendlich', 15.0 );
INSERT INTO MEMBER_TYPE (DESCRIPTION, AMOUNT) VALUES ( 'Fördermitglied', 10.0 );
INSERT INTO MEMBER_TYPE (DESCRIPTION, AMOUNT) VALUES ( 'Rabatt für Familienmitglieder', 15.0 );